import "./globals.css";
import Image from "next/image";
import logo from "@/public/logo.png";
import Link from "next/link";
import localFont from "next/font/local";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Oddval = localFont({
  src: [
    {
      path: "./fonts/Oddval-Black.ttf",
      weight: "900",
      style: "normal",
    },
    {
      path: "./fonts/Oddval-ExtraBold.ttf",
      weight: "800",
      style: "normal",
    },
    {
      path: "./fonts/Oddval-bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/Oddval-Semibold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "./fonts/Oddval-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/Oddval-Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Oddval-light.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-Oddval",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={Oddval.variable}>
      <body className="">
        <header className="w-full flex pt-[53px] justify-between items-center px-[122px] bg-[linear-gradient(221.81deg,#1C1F33_15.38%,#0A0B15_84.11%)]">
          <Image src={logo} alt={"logo"} />
          <div className="flex items-center gap-6">
            <Link href={"#"} className="text-int-red text-[20px]">
              Home
            </Link>
            <Link href={"#"} className="text-white text-[20px]">
              Explore
            </Link>
            <Link href={"#"} className="text-white text-[20px]">
              Discover
            </Link>
            <Link href={"#"} className="text-white text-[20px]">
              More
            </Link>
          </div>

          <div className=" flex gap-5">
            <button className="w-[156px] h-[46px] bg-int-red text-white hover:scale-105">
              Sign in
            </button>
            <button className="w-[156px] h-[46px] bg-transparent border-2 border-white text-white hover:scale-105">
              Sign in
            </button>
          </div>
        </header>

        {children}
      </body>
    </html>
  );
}
